#3131: Preliminary support for Oracle from Brook Schonfield

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -275,7 +275,7 @@ PACKAGE_BUGREPORT='rt-3.0-bugs@fsck.com'
 
 ac_unique_file="lib/RT.pm.in"
 ac_default_prefix=/opt/rt3
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS rt_version_major rt_version_minor rt_version_patch INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PERL SPEEDY_BIN exp_prefix exp_exec_prefix exp_bindir exp_sbindir exp_sysconfdir exp_mandir exp_libdir exp_datadir htmldir exp_htmldir manualdir exp_manualdir exp_localstatedir logfiledir exp_logfiledir masonstatedir exp_masonstatedir sessionstatedir exp_sessionstatedir customdir exp_customdir custometcdir exp_custometcdir customhtmldir exp_customhtmldir customlexdir exp_customlexdir customlibdir exp_customlibdir rt_layout_name RTGROUP BIN_OWNER LIBS_OWNER LIBS_GROUP DB_TYPE DB_HOST DB_PORT DB_RT_HOST DB_DBA DB_DATABASE DB_RT_USER DB_RT_PASS WEB_USER WEB_GROUP RT_VERSION_MAJOR RT_VERSION_MINOR RT_VERSION_PATCH RT_PATH RT_DOC_PATH RT_LOCAL_PATH RT_LIB_PATH RT_ETC_PATH CONFIG_FILE_PATH RT_BIN_PATH RT_SBIN_PATH RT_VAR_PATH RT_MAN_PATH MASON_DATA_PATH MASON_SESSION_PATH MASON_HTML_PATH LOCAL_ETC_PATH MASON_LOCAL_HTML_PATH LOCAL_LEXICON_PATH LOCAL_LIB_PATH DESTDIR RT_LOG_PATH LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS rt_version_major rt_version_minor rt_version_patch INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PERL SPEEDY_BIN exp_prefix exp_exec_prefix exp_bindir exp_sbindir exp_sysconfdir exp_mandir exp_libdir exp_datadir htmldir exp_htmldir manualdir exp_manualdir exp_localstatedir logfiledir exp_logfiledir masonstatedir exp_masonstatedir sessionstatedir exp_sessionstatedir customdir exp_customdir custometcdir exp_custometcdir customhtmldir exp_customhtmldir customlexdir exp_customlexdir customlibdir exp_customlibdir rt_layout_name RTGROUP BIN_OWNER LIBS_OWNER LIBS_GROUP DB_TYPE ORACLE_ENV_PREF DB_HOST DB_PORT DB_RT_HOST DB_DBA DB_DATABASE DB_RT_USER DB_RT_PASS WEB_USER WEB_GROUP RT_VERSION_MAJOR RT_VERSION_MINOR RT_VERSION_PATCH RT_PATH RT_DOC_PATH RT_LOCAL_PATH RT_LIB_PATH RT_ETC_PATH CONFIG_FILE_PATH RT_BIN_PATH RT_SBIN_PATH RT_VAR_PATH RT_MAN_PATH MASON_DATA_PATH MASON_SESSION_PATH MASON_HTML_PATH LOCAL_ETC_PATH MASON_LOCAL_HTML_PATH LOCAL_LEXICON_PATH LOCAL_LIB_PATH DESTDIR RT_LOG_PATH LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -803,8 +803,8 @@ Optional Packages:
   --with-bin-owner=OWNER  user that will own rt binaries (default root)
   --with-libs-owner=OWNER user that will own RT libraries (default root)
   --with-libs-group=GROUP group that will own rt binaries (default bin)
-  --with-db-type=TYPE     sort of database RT will use (default: mysql) (mysql
-                          and Pg are valid)
+  --with-db-type=TYPE     sort of database RT will use (default: mysql)
+                          (mysql, Oracle and Pg are valid)
   --with-db-host=HOSTNAME FQDN of database server (default: localhost)
   --with-db-port=PORT     port on which the database listens on
   --with-db-rt-host=HOSTNAME
@@ -1779,10 +1779,18 @@ if test "${with_db_type+set}" = set; then
 else
   DB_TYPE=mysql
 fi;
-if test "$DB_TYPE" != 'mysql' -a "$DB_TYPE" != 'Pg' -a "$DB_TYPE" != 'SQLite'; then
-	{ { echo "$as_me:$LINENO: error: Only Pg and mysql are valid db types" >&5
-echo "$as_me: error: Only Pg and mysql are valid db types" >&2;}
+if test "$DB_TYPE" != 'mysql' -a "$DB_TYPE" != 'Pg' -a "$DB_TYPE" != 'SQLite' -a "$DB_TYPE" != 'Oracle'; then
+	{ { echo "$as_me:$LINENO: error: Only Oracle, Pg and mysql are valid db types" >&5
+echo "$as_me: error: Only Oracle, Pg and mysql are valid db types" >&2;}
    { (exit 1); exit 1; }; }
+fi
+
+
+if test "$DB_TYPE" = 'Oracle'; then
+	test "x$ORACLE_HOME" = 'x' && { { echo "$as_me:$LINENO: error: Please declare the ORACLE_HOME environment variable" >&5
+echo "$as_me: error: Please declare the ORACLE_HOME environment variable" >&2;}
+   { (exit 1); exit 1; }; }
+	ORACLE_ENV_PREF="\$ENV{'ORACLE_HOME'} = '$ORACLE_HOME';"
 fi
 
 
@@ -2633,6 +2641,7 @@ s,@BIN_OWNER@,$BIN_OWNER,;t t
 s,@LIBS_OWNER@,$LIBS_OWNER,;t t
 s,@LIBS_GROUP@,$LIBS_GROUP,;t t
 s,@DB_TYPE@,$DB_TYPE,;t t
+s,@ORACLE_ENV_PREF@,$ORACLE_ENV_PREF,;t t
 s,@DB_HOST@,$DB_HOST,;t t
 s,@DB_PORT@,$DB_PORT,;t t
 s,@DB_RT_HOST@,$DB_RT_HOST,;t t
